### ISSUE TITLE
catkin_make error

### ISSUE THREAD

**Issue by shilaimu** [leggedrobotics/darknet_ros#101]
I can make successful with cpu
but have errors in gpu
CMake Error at darknet_ros_lib_generated_blas_kernels.cu.o.cmake:264 (message):
  Error generating file
  /home/xx/catkin_ws/build/darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/__/darknet/src/./darknet_ros_lib_generated_blas_kernels.cu.o

need your helps,please!

**Comment by shilaimu** [comment]
ubuntu 14.04
ros indigo
cuda 8.0.61

**Comment by shilaimu** [comment]
sorry, I had solved the error.

**Comment by yangy4444** [comment]
Hey, how did you solve the problem? Can you please share?
