### ISSUE TITLE
Subscribe to a kinect camera

### ISSUE THREAD

**Issue by catalin15dcm** [leggedrobotics/darknet_ros#109]
Hi,

I would like to make a node for kinect camera to get the 3d coordinaters of recognised object.
I think that i can give my node the information from bounding box topic and with the depth i can get those coordinates.

Can someone help me with writing this code?
Or
Is some code to get the 3d coordinates?

**Comment by shaarkrat2** [comment]
did you find a answer? i have the same problem

**Comment by astronaut71** [comment]
Yes, I have same issue. Would like to know the coordinate X,Y,Z of the detected Bounding Box. Any results how to do that?
