### ISSUE TITLE
fatal: Could not read from remote repository.

### ISSUE THREAD

**Issue by saurabhbajaj123** [leggedrobotics/darknet_ros#11]
When i run the command $ git clone --recursive git@github.com:leggedrobotics/darknet_ros.git

I get the following error

Cloning into 'darknet_ros'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by saurabhbajaj123** [comment]
What are the versions of
ubuntu
ROS
OpenCV
cuda
That you are running on?

**Comment by mbjelonic** [comment]
This sounds more like a general problem in your git setup. The following link might help: 

https://stackoverflow.com/questions/12940626/github-error-message-permission-denied-publickey
