### ISSUE TITLE
catkin_make error

### ISSUE THREAD

**Issue by shaarkrat2** [leggedrobotics/darknet_ros#127]
hi

when i use this command
`catkin_make -DCMAKE_BUILD_TYPE=Release`

i get this error

```
CMake Error at darknet_ros-master/darknet_ros/CMakeLists.txt:160 (add_library):
  Cannot find source file:

    DARKNET_PATH-NOTFOUND/src/activation_layer.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

CMake Error: CMake can not determine linker language for target: darknet_ros_lib
CMake Error: Cannot determine link language for target "darknet_ros_lib".
-- Generating done
-- Build files have been written to: /home/arnaud/yoloros_ws/build
Invoking "cmake" failed

```

i'm under ubuntu 16.04, with ros kinetic

Thanks

**Comment by shaarkrat2** [comment]
just install the packages with 
https://github.com/leggedrobotics/darknet_ros

**Comment by JayHsiang** [comment]
I have encountered this same problem, so what is the difference between this and the master branch?
```
CMake Error at /usr/share/cmake-3.5/Modules/FindCUDA.cmake:1649 (add_library):
  Cannot find source file:

    DARKNET_PATH-NOTFOUND/src/activation_layer.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
Call Stack (most recent call first):
  darknet_ros/darknet_ros/CMakeLists.txt:97 (cuda_add_library)


-- Generating done
-- Build files have been written to: /home/lab/ros/build
```
i'm also under ubuntu 16.04, with ros kinetic

Thanks

**Comment by ChunJyeBehBeh** [comment]
Hello, how you manage to solve it?

**Comment by JayHsiang** [comment]
@ChunJyeBehBeh 
just git the packages recursively with `git clone --recursive git@github.com:leggedrobotics/darknet_ros.git`

**Comment by zulfiz** [comment]
I am getting the same error. Here is the screenshot of my error
![image](https://user-images.githubusercontent.com/8537536/60112287-83b53180-973d-11e9-9c53-59c6b21f1e35.png)

I already cloned the library recursively using the command:
git clone --recursive git@github.com:leggedrobotics/darknet_ros.git

Could you please help me  @JayHsiang @shaarkrat2 @ChunJyeBehBeh in solving this issue. Thank you!

**Comment by 1329844541** [comment]
I have the same question.Did you solve it?

**Comment by JayHsiang** [comment]
@1329844541 
just git the packages recursively with
git clone --recursive git@github.com:leggedrobotics/darknet_ros.git
Remiand that --recursive is necessary.

**Comment by MccAlfh** [comment]
Setting the right path of DARKNET also can solve this problem，you can find the CMAKE log likes 

【-- +++ processing catkin package: 'darknet_ros'
-- ==> add_subdirectory(darknet_ros/darknet_ros)
-- Darknet path dir = /home/alfh/catkin_ws/src/darknet_ros-master/darknet】

Your darknet path should be corresponding to “-- Darknet path dir = /home/alfh/catkin_ws/src/darknet_ros-master/darknet”
may this be helpful！

**Comment by everardo07** [comment]
Hello 

I have the same question? How do you solve the problem , cause I tried the solutions showed in the previous comments but nothing works.

**Comment by mf093087** [comment]
> Hello
> 
> I have the same question? How do you solve the problem , cause I tried the solutions showed in the previous comments but nothing works.

Me too, nothing works

**Comment by SkyWxxk** [comment]
I met the  same problem, because I downloaded it  by typing
`git clone https://github.com/leggedrobotics/darknet_ros.git`
Later I added the` --recursive ` like 
`git clone --recursive https://github.com/leggedrobotics/darknet_ros.git`
Then compiled successfully

**Comment by bibinthomas007** [comment]
If you haven't used --recursive flag while cloning the repository, do the below steps.
Navigate to the darknet_ros directory inside your ws
```
cd ~/catkin_ws/src/darknet_ros
``` 

Initialize and update the submodules:
```
git submodule update --init --recursive
``` 

next do 
 
```
catkin_make
``` 
then, 
```
catkin_make -DCMAKE_BUILD_TYPE=Release
```
