### ISSUE TITLE
Tiny Yolo V3 version

### ISSUE THREAD

**Issue by pnambiar** [leggedrobotics/darknet_ros#138]
Does tiny yolo V3 version work with tis wrapper?

**Comment by tooskoolforkool** [comment]
Yes

- Create a yolov3_tiny.yaml file in cfg directory and make sure it has the correct information
- Download yolov3_tiny.weights and yolov3_tiny.cfg to the neural_network_config file
- Create a launch file to run yolov3_tiny

**Comment by mbjelonic** [comment]
Thanks for the answer!

**Comment by ican9595** [comment]
@tarek-mahmoud thanks for the answer but dont I need also the pretrained yolov3-tiny.conv file to train my custom object? where can I download that?

**Comment by tarek-mahmoud** [comment]
@ican9595 go to https://pjreddie.com/darknet/yolo/ and you will find two hyperlinks per entry. One for the weights and one for the cfg. 

To train the model, I recommend you follow the instructions outlined in this repo: https://github.com/AlexeyAB/darknet

After training from that repo, you can use the model you trained and port it into your ROS nodes using leggedrobotics's darknet_ros repo
