### ISSUE TITLE
libdarknet_ros_lib.so:  undefined reference to `ipl_into_image'....where is the function "ipl_into_image" ?

### ISSUE THREAD

**Issue by koalamaster** [leggedrobotics/darknet_ros#147]
[ 61%] Linking CXX shared library /home/nvidia/BLland_ws/devel/lib/libdarknet_ros_lib.so
[ 98%] Built target darknet_ros_lib
[ 98%] Linking CXX executable /home/nvidia/BLland_ws/devel/lib/darknet_ros/darknet_ros
**/home/nvidia/BLland_ws/devel/lib/libdarknet_ros_lib.so: undefined reference to `ipl_into_image'**
collect2: error: ld returned 1 exit status

**Comment by koalamaster** [comment]
where is the function "ipl_into_image" ?

**Comment by koalamaster** [comment]
solved

**Comment by FiveHamburgers** [comment]
Hi, i have the same problem with you, could you tell me how do you solve the 'undefined reference to `ipl_into_image'? Thanks a lot!

**Comment by dengjianbo3** [comment]
Hey, could you tell me how to solve this problem, thanks

**Comment by Miguel-GitHub** [comment]
I have exactly the same problem. Please, if anyone knows the solution, it would be appreciated if you published it. Thank you.
