### ISSUE TITLE
RTSP stream instead of webcam

### ISSUE THREAD

**Issue by mmilunovic** [leggedrobotics/darknet_ros#174]
How should I change the ros.yaml file in order to use RTSP stream instead of usb_cam?

**Comment by lchop** [comment]
Hello, you should use this package (http://wiki.ros.org/video_stream_opencv) that convert an rtsp stream to images published in a ROS topic then subscribe to this topic by changing the topic name in the ros.yaml.

**Comment by tomlankhorst** [comment]
Thanks for the tip.
