### ISSUE TITLE
In correct range

### ISSUE THREAD

**Issue by tanakataiki2** [leggedrobotics/darknet_ros#176]
I use ros kinetic Ubuntu 16.04LTS

 I cloned and successfully build repo

199100K .......... .......... .......... .......... .......... 99% 4.41M 0s
199150K ....                                                  100% 10.1M=47s

cd /home/taiki/catkin_darknet/build/darknet_ros; catkin build --get-env darknet_ros | catkin env -si  /usr/bin/cmake /home/taiki/catkin_darknet/src/darknet_ros/darknet_ros --no-warn-unused-cli -DCATKIN_DEVEL_PREFIX=/home/taiki/catkin_darknet/devel/.private/darknet_ros -DCMAKE_INSTALL_PREFIX=/home/taiki/catkin_darknet/install; cd -
...............................................................................
Finished  <<< darknet_ros                          [ 2 minutes and 21.9 seconds ]
[build] Summary: All 3 packages succeeded!                                     
[build]   Ignored:   None.                                                     
[build]   Warnings:  1 packages succeeded with warnings.                       
[build]   Abandoned: None.                                                     
[build]   Failed:    None.                                                     
[build] Runtime: 2 minutes and 29.7 seconds total.                             
[build] Note: Workspace packages have changed, please re-source setup files to use them.
... logging to /home/taiki/.ros/log/b9545c40-ba96-11e9-8559-0cc47aaaafe3/roslaunch-ttanakaUbuntu16-16871.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

but when I type this command after roscore
 rosrun usb_cam usb_cam_node /usb_cam/image_raw:=/camera/image_raw
following error has shown up

[ INFO] [1565350700.043072626]: using default calibration URL
[ INFO] [1565350700.043220537]: camera calibration URL: file:///home/taiki/.ros/camera_info/head_camera.yaml
[ INFO] [1565350700.043327235]: Unable to open camera calibration file [/home/taiki/.ros/camera_info/head_camera.yaml]
[ WARN] [1565350700.043380128]: Camera calibration file /home/taiki/.ros/camera_info/head_camera.yaml not found.
[ INFO] [1565350700.043439845]: Starting 'head_camera' (/dev/video0) at 640x480 via mmap (mjpeg) at 30 FPS
[mjpeg @ 0xbb60e0] Changeing bps to 8
[mjpeg @ 0xbb60e0] mjpeg_decode_dc: bad vlc: 0:0 (0xbb67c8)
[mjpeg @ 0xbb60e0] error dc
[mjpeg @ 0xbb60e0] error y=59 x=17
[swscaler @ 0xbcdc20] deprecated pixel format used, make sure you did set range correctly

Can you tell me where to change first?
I think it's because incorrect image size input?

Thanks you for a good repo!

**Comment by tomlankhorst** [comment]
This should be solved in a recent version.
