### ISSUE TITLE
Port for ROS2?

### ISSUE THREAD

**Issue by NovoG93** [leggedrobotics/darknet_ros#177]
Will there be a port for ROS2?

**Comment by cardboardcode** [comment]
Hi @NovoG93 , I am interested in this issue as well. 

@mbjelonic , are there any plans for this port? If not, I am willing to invest some bandwidth to address this issue.

**Comment by fmrico** [comment]
Hi @NovoG93 @cardboardcode 

I have just ported darknet_ros to ROS2. To make a PR, @mbjelonic , could you make a ros2 (or the name you prefer) branch?

![Captura de pantalla de 2020-01-14 18-43-27](https://user-images.githubusercontent.com/3810011/72368784-03691480-36ff-11ea-9964-ba0484eed9cf.png)


Enjoy!!!

**Comment by mbjelonic** [comment]
Hi all,
thank you for porting the software to ROS2. I just created a new branch called ros2. Looking forward to the PR.
Best,
Marko

**Comment by cardboardcode** [comment]
@fmrico 

Awesome work. Thank you so much. 

Will be checking it out soon.

**Comment by fmrico** [comment]
Thanks!!!!

I have just made the PR in #206 

Best
Francisco

**Comment by tomlankhorst** [comment]
See https://github.com/leggedrobotics/darknet_ros/tree/foxy
