### ISSUE TITLE
Output Window Not Responding

### ISSUE THREAD

**Issue by itsmomito** [leggedrobotics/darknet_ros#179]
When i try to run darknet_ros.launch or any other launch files, a window appears and momentarily stops responding, no further information is displayed. I modified ros.yaml to subscribe to camera image topic and tested that the images are being displayed using "rosrun image_view image_view image:=/openmv_cam/image_raw" so I'm not sure what the issue is. 

![image](https://user-images.githubusercontent.com/245854/65301192-42a99f00-db2b-11e9-949e-3a7c0a1641ac.png)

started roslaunch server http://ubuntu:38873/

SUMMARY
========

PARAMETERS
 * /darknet_ros/actions/camera_reading/name: /darknet_ros/chec...
 * /darknet_ros/config_path: /home/itsmomito/c...
 * /darknet_ros/image_view/enable_console_output: True
 * /darknet_ros/image_view/enable_opencv: True
 * /darknet_ros/image_view/wait_key_delay: 1
 * /darknet_ros/publishers/bounding_boxes/latch: False
 * /darknet_ros/publishers/bounding_boxes/queue_size: 1
 * /darknet_ros/publishers/bounding_boxes/topic: /darknet_ros/boun...
 * /darknet_ros/publishers/detection_image/latch: True
 * /darknet_ros/publishers/detection_image/queue_size: 1
 * /darknet_ros/publishers/detection_image/topic: /darknet_ros/dete...
 * /darknet_ros/publishers/object_detector/latch: False
 * /darknet_ros/publishers/object_detector/queue_size: 1
 * /darknet_ros/publishers/object_detector/topic: /darknet_ros/foun...
 * /darknet_ros/subscribers/camera_reading/queue_size: 1
 * /darknet_ros/subscribers/camera_reading/topic: /openmv_cam/image...
 * /darknet_ros/weights_path: /home/itsmomito/c...
 * /darknet_ros/yolo_model/config_file/name: yolov2-tiny.cfg
 * /darknet_ros/yolo_model/detection_classes/names: ['person', 'bicyc...
 * /darknet_ros/yolo_model/threshold/value: 0.3
 * /darknet_ros/yolo_model/weight_file/name: yolov2-tiny.weights
 * /rosdistro: indigo
 * /rosversion: 1.11.21

NODES
  /
    darknet_ros (darknet_ros/darknet_ros)

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
process[darknet_ros-1]: started with pid [12886]
[ INFO] [1568956622.303295422]: [YoloObjectDetector] Node started.
[ INFO] [1568956622.311792371]: [YoloObjectDetector] Xserver is running.
[ INFO] [1568956622.314425255]: [YoloObjectDetector] init().
YOLO V3
layer     filters    size              input                output
    0 conv     16  3 x 3 / 1   416 x 416 x   3   ->   416 x 416 x  16  0.150 BFLOPs
    1 max          2 x 2 / 2   416 x 416 x  16   ->   208 x 208 x  16
    2 conv     32  3 x 3 / 1   208 x 208 x  16   ->   208 x 208 x  32  0.399 BFLOPs
    3 max          2 x 2 / 2   208 x 208 x  32   ->   104 x 104 x  32
    4 conv     64  3 x 3 / 1   104 x 104 x  32   ->   104 x 104 x  64  0.399 BFLOPs
    5 max          2 x 2 / 2   104 x 104 x  64   ->    52 x  52 x  64
    6 conv    128  3 x 3 / 1    52 x  52 x  64   ->    52 x  52 x 128  0.399 BFLOPs
    7 max          2 x 2 / 2    52 x  52 x 128   ->    26 x  26 x 128
    8 conv    256  3 x 3 / 1    26 x  26 x 128   ->    26 x  26 x 256  0.399 BFLOPs
    9 max          2 x 2 / 2    26 x  26 x 256   ->    13 x  13 x 256
   10 conv    512  3 x 3 / 1    13 x  13 x 256   ->    13 x  13 x 512  0.399 BFLOPs
   11 max          2 x 2 / 1    13 x  13 x 512   ->    13 x  13 x 512
   12 conv   1024  3 x 3 / 1    13 x  13 x 512   ->    13 x  13 x1024  1.595 BFLOPs
   13 conv    512  3 x 3 / 1    13 x  13 x1024   ->    13 x  13 x 512  1.595 BFLOPs
   14 conv    425  1 x 1 / 1    13 x  13 x 512   ->    13 x  13 x 425  0.074 BFLOPs
   15 detection
mask_scale: Using default '1.000000'
Loading weights from /home/itsmomito/catkin_ws/src/darknet_ros/darknet_ros/yolo_network_config/weights/yolov2-tiny.weights...Done!
Waiting for image.

**Comment by MrParris** [comment]
The last line "Waiting for image."
Got it too, when I first started to use this node. The problem might be that your don't remap properly your video feed provider's topic. Look into /home/itsmomito/catkin_ws/src/darknet_ros/darknet_ros/config/ and check wich .yaml file you're using. For instance in ros.yaml at the line ''camera_reading'', it describes the video feed provider's topic name(the right one defined by the camera or the webcam node, so in my case I used a realsense camera so I had a realsense camera node defining its own video feed topic i.e : /camera/rgb/image_rect_color instead of ''something/image_raw'').
