### ISSUE TITLE
YoloObjectDetector.cpp  failed 

### ISSUE THREAD

**Issue by developermastermind07** [leggedrobotics/darknet_ros#180]
I am trying to make but everytime i am getting following error

[ 46%] Building NVCC (Device) object darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/__/darknet/src/darknet_ros_lib_generated_convolutional_kernels.cu.o
Scanning dependencies of target darknet_ros_lib
[ 47%] Building CXX object darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/src/YoloObjectDetector.cpp.o
c++: error: unrecognized command line option ‘-std=gnu++14’
darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/build.make:1796: recipe for target 'darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/src/YoloObjectDetector.cpp.o' failed
make[2]: *** [darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/src/YoloObjectDetector.cpp.o] Error 1
CMakeFiles/Makefile2:2708: recipe for target 'darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/all' failed
make[1]: *** [darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by tomlankhorst** [comment]
The package has been modified significantly over time so hopefully, this issue is resolved.
