### ISSUE TITLE
How to test an image with zed camera?

### ISSUE THREAD

**Issue by kctoayo88** [leggedrobotics/darknet_ros#192]
Hello,
The default detecting way is keeping detect a real-time video from camera.
So I want to captured an image, then input it to YOLO model to detect objects with c++ node. 

Is there anyone know how to do it?
If you could provide me some example code, it will be nice to me!

Thanks!

**Comment by YangSiri** [comment]
Hi, @kctoayo88 
I'm also testing using ZED.  I recorded the image data in rosbags. But i dont know how to detect it using this. I changed the topic name. It didnt work. Do you have any comments? 
Have tested this in real-time camera ?

Looking forward to your reply. THANKS

**Comment by mtbsteve** [comment]
You need to have the ZED ROS wrapper installed and then launch it with 
`roslaunch zed_wrapper zed.launch`
in the darknet_ros.launch file set the desired zed node as input:
`<arg name="image" default="/zed/zed_node/left/image_rect_color" />`
Works perfectly fine for me.
