### ISSUE TITLE
How can I use AlexeyAB version darknet,not the leggedrobotics'?

### ISSUE THREAD

**Issue by Shame-fight** [leggedrobotics/darknet_ros#195]
Thanks for your work,I want to use darknet on ros,the AlexeyAB'darknet is better than  leggedrobotics',But the code does not match the AB version.how can I use it,can you help me? the link is https://github.com/AlexeyAB/darknet 
Looking forward to your reply.
@ronwalf @alexmillane @ompugao @rmmcnulty9 @umer936

**Comment by pushkalkatara** [comment]
Hi @Shame-fight Some time ago I did the AlexeyAB clone of darknet_ros. You can find it here - https://github.com/pushkalkatara/darknet_ros

**Comment by Shame-fight** [comment]
> Hi @Shame-fight Some time ago I did the AlexeyAB clone of darknet_ros. You can find it here - https://github.com/pushkalkatara/darknet_ros

I am very happy to hear from you.In fact, I have tried your version on the PC, but I have a problem: when the target is detected, the process will be killed; even if the target is not detected, the same situation will occur after 1-2 minutes, I am not Know how to solve this problem.I look forward to using your code.

**Comment by RhysMcK** [comment]
> Influenced from Memory Leak Issue on leggedrobotics/darket_ros repository. While running the ROS Node on Jetson TX1, the node was being killed in some time due to overflow in memory. This repository solves the issue of memory leak implementing multithreading techniques.

was that it?

**Comment by Shame-fight** [comment]
> > Influenced from Memory Leak Issue on leggedrobotics/darket_ros repository. While running the ROS Node on Jetson TX1, the node was being killed in some time due to overflow in memory. This repository solves the issue of memory leak implementing multithreading techniques.
> 
> was that it?

sorry, I failed to run successfully, the program will be interrupted immediately when the target is detected. You can try to run this program normally.

**Comment by tomlankhorst** [comment]
The package has changed a lot over time. Please feel free to open a new issue for current problems.
