### ISSUE TITLE
error "OpenCV 4.x+ requires enabled C++11 support"

### ISSUE THREAD

**Issue by Ajaygirish1** [leggedrobotics/darknet_ros#200]
`Hey` all,
I am facing the below error,
error "OpenCV 4.x+ requires enabled C++11 support" while executing catkin make,
I have tried inserting 
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED TRUE)
in Cmake.txt of darknet_ros node but still doesnt work.
![Screenshot from 2019-11-25 05-42-03](https://user-images.githubusercontent.com/57762043/69512938-61228100-0f46-11ea-8a15-023c79186abc.png)
[CMakeLists.txt](https://github.com/leggedrobotics/darknet_ros/files/3884874/CMakeLists.txt)

**Comment by cardboardcode** [comment]
You can try have a look at **pull request #202** by @kunaltyagi. 

Compiled the version under this fork and it solved the compilation issue. 

Hope this helps.

**Comment by mywnajsldkf** [comment]
which openCV version do you use??

**Comment by kunaltyagi** [comment]
I use OpenCV@HEAD

**Comment by mywnajsldkf** [comment]
@kunaltyagi oh! thank you for answering. I installed opencv3.4.6, after catkin_make darknet_ros, I met error "OpenCV 4.x+ requires enabled C++11 support" can I you your solution(https://github.com/leggedrobotics/darknet_ros/pull/202/commits/256ea5050a866dbd3973046428dcaeecc390a148 by following this commit) to solve my problem??

**Comment by mywnajsldkf** [comment]
I want to use darknet_ros to detect something!! i

**Comment by kunaltyagi** [comment]
> I installed opencv3.4.6, after catkin_make darknet_ros, I met error "OpenCV 4.x+ requires enabled C++11 support" can I you your solution(256ea50 by following this commit) to solve my problem??

You have OpenCV 4 not 3 installed, and yes, my fork works with latest OpenCV and ROS. If you want to work on darknet directly, I'd recommend https://github.com/alexeyab/darknet instead.

**Comment by mywnajsldkf** [comment]
> > I installed opencv3.4.6, after catkin_make darknet_ros, I met error "OpenCV 4.x+ requires enabled C++11 support" can I you your solution([256ea50](https://github.com/leggedrobotics/darknet_ros/commit/256ea5050a866dbd3973046428dcaeecc390a148) by following this commit) to solve my problem??
> 
> You have OpenCV 4 not 3 installed, and yes, my fork works with latest OpenCV and ROS. If you want to work on darknet directly, I'd recommend https://github.com/alexeyab/darknet instead.

Oh, I'm sorry for bothering you
But when I enter `pkg_config --modeversion opencv` opencv3.4.6 show up. also I tested it on python. And I want to detect on ROS.

**Comment by prit-ubuntu** [comment]
@Ajaygirish1 and @mywnajsldkf did you end up finding a solution? I am facing the same problems. I'm using Ubuntu 18.04 and OpenCV 3.4.0 for this purpose.

**Comment by mywnajsldkf** [comment]
@prit-ubuntu Do you want to use OpenCV 3.4.0 for using darknet_ros? If you want it, I recommend following this procedure
1.  Delete OpenCV already installed your hardware! 
`sudo find / -name "*opencv*" -exec rm -i {} \;`
2. Install OpenCV (https://jkjung-avt.github.io/opencv-on-nano/)
i recommend this blog. And If you use ROS version1, ROS default python package is `python2.7`. So I changed shell script a little to install OpenCV 3.4.6 on python2

**Comment by prit-ubuntu** [comment]
@mywnajsldkf so basically the solution you mentioned above worked for you to run darknet_ros? Yes, i do want to use OpenCV 3.4.0 for darknet_ros.

**Comment by mywnajsldkf** [comment]
@prit-ubuntu It is best for me!

**Comment by kunaltyagi** [comment]
You can also use my fork (I really should move it to point to AlexyAB's implementation)

**Comment by prit-ubuntu** [comment]
@mywnajsldkf and @kunaltyagi I'm happy to inform you that I have finally managed to compile darknet_ros on my system! Thanks for your help.

**Comment by Silerqin** [comment]
hi, I am getting the same issue. Can I know how to solve it? @kunaltyagi I have see your fork, can I know how to install it?

**Comment by kunaltyagi** [comment]
There are other more up-to-date PRs. My fork has been unmaintained for a while so I personally wouldn't recommend it. See #257 and @230

However, my fork still works if you still want to use it. Please use the opencv4 branch, and clone it (with submodules) in your workspace (or underlay of that workspace) 😄

**Comment by Silerqin** [comment]
@kunaltyagi I already use openCV4 but it still have error

**Comment by tomlankhorst** [comment]
Support for OpenCV4 seems to be lagging a little. Maybe @mbjelonic has an indication of if and when it might come. 
@ranjitkathiriya
