### ISSUE TITLE
Can I use .pb file or .ckpt file as my weights?

### ISSUE THREAD

**Issue by anne841124** [leggedrobotics/darknet_ros#215]
I have already trained my data, but its saved as .ckpt file.
Is there have any way to use .ckpt file as weights in this ROS package?

**Comment by fiorano10** [comment]
You can't, did you train using pytorch? Try this [pytorch darknet ](https://github.com/yehengchen/YOLOv3-ROS/tree/master/yolov3_pytorch_ros)

**Comment by tomlankhorst** [comment]
Seems like #242, maybe @dregner has a solution for you.
