### ISSUE TITLE
Problems with Intel Real Sense D435i

### ISSUE THREAD

**Issue by Philipp385** [leggedrobotics/darknet_ros#218]
Hello,

i wanted to start detecting custom objects with my Intel Real Sense and trained weights from YoloV3. Therefore i installed the IR Package from https://github.com/IntelRealSense/realsense-ros
and the darknet-ros package from here (https://github.com/leggedrobotics/darknet_ros).
I have already trained yolo on a custom dataset and put the weight-file in the weights folder and the cfg-file in the cfg folder. Then I edited the ros.yaml file to the Topic "/camera/color/image_raw" from the IntelRealSense and generated a yaml file for my custom objects as you can see here:
![grafik](https://user-images.githubusercontent.com/61509897/75673234-c8a54680-5c82-11ea-9658-b4bb7aaceed2.png)
I edited the darknet_ros launch file in line 14 to point to my yaml file:
![grafik](https://user-images.githubusercontent.com/61509897/75673056-5af91a80-5c82-11ea-95fc-518bcb711f85.png)
In the next step I started (each in an extra terminal) the roscore, IntelRealSense Node (roslaunch realsense2_camera rs_camera.launch) and the darknet ros launch file (roslaunch darknet_ros darknet_ros.launch) and i get the result:
![GetImage](https://user-images.githubusercontent.com/61509897/75673569-8a5c5700-5c83-11ea-8c8e-2518d5eeb3ca.png)
But after a time i get the following error:
![GetImage(1)](https://user-images.githubusercontent.com/61509897/75673616-a8c25280-5c83-11ea-9f33-e06942193cde.png)

Has anyone an idea what causes this problem and could please help me to find a solution? Is there a mistake i made?

Thank you in advance.

**Comment by Philipp385** [comment]
I solved the Problem. It was the sharp S in "Stator groß", that caused the problem. Everytime YOLO detected the "Stator groß" all processes died.

**Comment by hsaleem1** [comment]
@Philipp385,
Please help me.
I have installed the package darknet_ros
Now I ran roscore, Intel Realsense node and darknet_ros nodes.
What should I do next? should I type rviz in the other terminal or what not?
