### ISSUE TITLE
ERROR: cannot launch node of type [darknet_ros/darknet_ros]

### ISSUE THREAD

**Issue by Dimitrios-Ar** [leggedrobotics/darknet_ros#220]
Hi all. Been struggling a couple of days to be able to use the package. I have this problem when using the launch file.

aut@dim:~/catkin_ws/src/darknet_ros/darknet_ros/launch$ roslaunch yolo_v3.launch 
... logging to /home/aut/.ros/log/8d7cbbc4-66cd-11ea-bb18-e0d55e07a55f/roslaunch-dim-465.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/loader.py:412: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(text)
started roslaunch server http://dim:41197/

SUMMARY
========

PARAMETERS
 * /darknet_ros/actions/camera_reading/name: /darknet_ros/chec...
 * /darknet_ros/config_path: /home/aut/catkin_...
 * /darknet_ros/image_view/enable_console_output: True
 * /darknet_ros/image_view/enable_opencv: True
 * /darknet_ros/image_view/wait_key_delay: 1
 * /darknet_ros/publishers/bounding_boxes/latch: False
 * /darknet_ros/publishers/bounding_boxes/queue_size: 1
 * /darknet_ros/publishers/bounding_boxes/topic: /darknet_ros/boun...
 * /darknet_ros/publishers/detection_image/latch: True
 * /darknet_ros/publishers/detection_image/queue_size: 1
 * /darknet_ros/publishers/detection_image/topic: /darknet_ros/dete...
 * /darknet_ros/publishers/object_detector/latch: False
 * /darknet_ros/publishers/object_detector/queue_size: 1
 * /darknet_ros/publishers/object_detector/topic: /darknet_ros/foun...
 * /darknet_ros/subscribers/camera_reading/queue_size: 1
 * /darknet_ros/subscribers/camera_reading/topic: /camera/rgb/image...
 * /darknet_ros/weights_path: /home/aut/catkin_...
 * /darknet_ros/yolo_model/config_file/name: yolov3.cfg
 * /darknet_ros/yolo_model/detection_classes/names: ['person', 'bicyc...
 * /darknet_ros/yolo_model/threshold/value: 0.3
 * /darknet_ros/yolo_model/weight_file/name: yolov3.weights
 * /rosdistro: melodic
 * /rosversion: 1.14.3

NODES
  /
    darknet_ros (darknet_ros/darknet_ros)

auto-starting new master
process[master]: started with pid [476]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 8d7cbbc4-66cd-11ea-bb18-e0d55e07a55f
process[rosout-1]: started with pid [509]
started core service [/rosout]
ERROR: cannot launch node of type [darknet_ros/darknet_ros]: can't locate node [darknet_ros] in package [darknet_ros]

Any ideas? Thanks in advance for your time.

**Comment by NerminSalem** [comment]
@Dimitrios-Ar how did u solve that issue?
thanks
