### ISSUE TITLE
Low fps : 3.0

### ISSUE THREAD

**Issue by q8wwe** [leggedrobotics/darknet_ros#228]
Jetson Tx2
Ubuntu 16.04
ROS kinetic

Hello , 

I updated opencv to 3.4.2 and installEd Yolo3 . But I'm getting low fps between 3.0 to 3.3 .

How can I increase the fps , I will appreciate if someone can advice Mr.

**Comment by tomlankhorst** [comment]
Make sure to compile your code in release mode.
