### ISSUE TITLE
How to compute quaternion from max and min coordinate values of the Bounding Boxes?

### ISSUE THREAD

**Issue by astronaut71** [leggedrobotics/darknet_ros#229]
I am facing some problem in creating the orientation of the Bounding Box of the detected objects in ROS). I know the max and min coordinate values (xmin, xmax, ymin, ymax, zmin, zmax). So, I can easily find the vertex of the objects Bounding BOX (Cube) which are 
```
[xmin ymin zmin; 
 xmax ymin zmin; 
 xmax ymax zmin; 
 xmin ymax zmin;
 xmin ymin zmax; 
 xmax ymin zmax; 
 xmax ymax zmax;
 xmin ymax zmax]
```
Now how can I create the quaternion from these vertex in order to get the orientation of the bounding box? I know that a quaternion is a set of 4 numbers, [x y z w], which represents rotations the following way:

x = RotationAxis.x * sin(RotationAngle / 2)
y = RotationAxis.y * sin(RotationAngle / 2)
z = RotationAxis.z * sin(RotationAngle / 2)
w = cos(RotationAngle / 2)

How to get the RotationAxis and RotationAngle when knowing the vertex of the object (in my case is a cube or 3D rectangle)? Thanks

**Comment by tomlankhorst** [comment]
Darknet returns bounding boxes in image space. The bounding boxes are not rotated. You'll have to estimate the coordinates in world space on your own, which is not trivial. It's out of the scope of this package but if you have some thought on it, feel free to share.
