### ISSUE TITLE
Cannot catkin_make

### ISSUE THREAD

**Issue by Kn15263ss** [leggedrobotics/darknet_ros#23]
Hi~ I have a little problem
I use ubuntu 14.04 , ROS:indigo
When i catkin_make, i encounter a problem:
![image](https://user-images.githubusercontent.com/22387638/29181789-00addd7e-7e2f-11e7-84c3-9d0873805299.png)
![image](https://user-images.githubusercontent.com/22387638/29181794-050f53de-7e2f-11e7-95a1-3a9b2ef1f313.png)

How to fix this problem?
Thanks you!

**Comment by mbjelonic** [comment]
Hi, 
I think the gnu compiler 4.8 does not fully support c++11. Please try to use gnu 4.9.2 or higher. For reference: I am using version 5.4.0 on my tx2.
Best,
Marko

**Comment by Kn15263ss** [comment]
I have install gcc version 4.8.5 and g++ version 7.1.0, and I don't know what is gnu.

**Comment by mbjelonic** [comment]
Check out this: https://gcc.gnu.org/

Updating gcc is exactly what I meant. Is it still not working?

**Comment by Kn15263ss** [comment]
Yes! It is still not working

**Comment by Hothaifa** [comment]
I had the same problem and i'm still using gcc 4.8. you can fix it by adding --std=c++11 to NVCC_FLAG in the CMakeLists.txt. i created a pull request about this problem

**Comment by BolinZhou** [comment]
I think this has to do with the darknet architecture supports. I think the original darknet had commoned out the line `-gencode arch=compute_20,code=[sm_20,sm_21]` of the [ darknet_ros/darknet_ros/CMakeLists.txt](url) try it without that line
