### ISSUE TITLE
Headless usage? X11 not found

### ISSUE THREAD

**Issue by fwarmuth** [leggedrobotics/darknet_ros#233]
Hey,
i am trying to run within a docker container on a headless machine.
But `catkin build` tells me that X11 is missing, because it is:
```
Errors     << darknet_ros:cmake /workspace/ros_ws/logs/darknet_ros/build.cmake.001.log
CMake Error at /usr/share/cmake-3.10/Modules/FindX11.cmake:429 (message):
  Could not find X11
Call Stack (most recent call first):
  CMakeLists.txt:40 (find_package)


cd /workspace/ros_ws/build/darknet_ros; catkin build --get-env darknet_ros | catkin env -si  /usr/bin/cmake /workspace/ros_ws/src/inference-module/darknet_ros/darknet_ros --no-warn-unused-cli -DCATKIN_DEVEL_PREFIX=/workspace/ros_ws/devel/.private/darknet_ros -DCMAKE_INSTALL_PREFIX=/workspace/ros_ws/install; cd -
```
This there a way to get this running within an Docker without installing X11?
How do you guy deploy this on embedded machines?
regards

**Comment by tomlankhorst** [comment]
The X11 dependency should be factored out. However, it is possible to install x11 on a headless box as well. These (rosdep) dependencies should do: 

- libx11
- libxt-dev
- libxext
