### ISSUE TITLE
Why use SSH to clone this repository?

### ISSUE THREAD

**Issue by willzoe** [leggedrobotics/darknet_ros#235]
I used the `git clone` command to clone this repository by `HTTPS` to my catkin workspace, and an error occurred during compilation.

Later, I followed the prompts in the `README` and used `SSH` to clone this repository. The package can be compiled correctly.

I want to know what is the difference between using HTTP cloning and SSH cloning?

**Comment by tomlankhorst** [comment]
There should be no difference. Could you have missed the  `--recursive` flag the first time when you were cloning with HTTPS?

**Comment by willzoe** [comment]
I did miss this parameter. 

What is the role of this parameter? If this parameter is not used, will the repository be missing some files?

**Comment by tomlankhorst** [comment]
This repository contains a [submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules), that's like another repository in this repository. The `--recursive` flags indicates that `git` should clone these sub repositories too.
