### ISSUE TITLE
Does this code support CUDA10.2?

### ISSUE THREAD

**Issue by Looomo** [leggedrobotics/darknet_ros#237]
Does this code support CUDA10.2? Cause I modified Makefile in Darknet folder to use or not use CUDA or CUDNN but it was always 11 or 12 FPS . Actually when I test the darknet yolov3 (not ros version) it does changed ( 130 ms using CUDNN , 350ms not using  ) . Can anyone please help ? Really want to make it faster . also sorry about my bad English

**Comment by tomlankhorst** [comment]
I am sorry for this late reply. Were you able to resolve this issue? 

Your English does not need any excuses. :)
