### ISSUE TITLE
Is it for yolov1?

### ISSUE THREAD

**Issue by joyyang1215** [leggedrobotics/darknet_ros#24]
How could I modify the CMakeLists.txt to implement yolov2 for ROS version?
Could you tell me some hints?

**Comment by mbjelonic** [comment]
Hi,

This repo is using yolov2 and not yolov1. So you do not need to change anything.

Best,
Marko

**Comment by joyyang1215** [comment]
I got it, finally I saw its title: YOLO V2 object detection
thank you so much
