### ISSUE TITLE
How to detect from a video file

### ISSUE THREAD

**Issue by SKEW002** [leggedrobotics/darknet_ros#244]

**Comment by diegocdl** [comment]
Hi @SKEW002 I used a package to read the video file and stream it as an Image topic which can be given to the darknet_ros.
You can check this: http://wiki.ros.org/video_stream_opencv

**Comment by tomlankhorst** [comment]
@SKEW002 Please report on the problem status so far. Did @deigocdl's solution work for you?

**Comment by tomlankhorst** [comment]
Assuming @diegocdl's solution worked. If not, reopen.
