### ISSUE TITLE
Bounding Boxes not being displayed

### ISSUE THREAD

**Issue by AndreejS** [leggedrobotics/darknet_ros#246]
I am using the yolov3.yaml as the network_param_file. The object detection is working and i also get the percentages shown in the console. However, i do not get any bounding boxes displayed. 

Are there any limitations to the image size ? Our camera sensor creates 128x128 images.

The only thing i found was, that the YoloObjectDetector.hpp has the following errors:
![Screenshot from 2020-06-14 21-27-52](https://user-images.githubusercontent.com/39523653/84602215-06228e00-ae86-11ea-8d69-eb3d4956fae1.png)
(cannot open source file error)

Also, i can not import the BoundingBox.msg or any other .msg from a different node.
![Screenshot from 2020-06-14 21-30-38](https://user-images.githubusercontent.com/39523653/84602255-5568be80-ae86-11ea-85ba-3bf437556abb.png)

Can anyone provide some hints on how to solve the problem ?

**Comment by tomlankhorst** [comment]
If everything compiles then the includes are found by the compiler. So this might have to do with your IDE configuration. That doesn't explain the bounding boxes issue though. Did you find a solution? 
To pin down whether it's due to your relatively small image size, you could try to feed a large image instead.

**Comment by AndreejS** [comment]
The bounding box problem was due to the image resolution the camera sensor was producing. The sensor was producing 128x128 images, we increased that to 500x500 and the bounding boxes were displayed afterwards. Thanks for your hint!

We still did not found the reason for our IDE not recognizing the msg which darknet_ros produces. We are using Vscode, any hints ?

**Comment by tomlankhorst** [comment]
That probably has to do with the include paths. You might want to source your workspace in a terminal (e.g. source devel/setup.bash) and load VSCode after that. If it remains a problem feel free to open a new issue.
