### ISSUE TITLE
what's means the BoundingBox.msg

### ISSUE THREAD

**Issue by liangpu597** [leggedrobotics/darknet_ros#249]
I have question about the darknet_ros/darknet_ros_msgs/msg/BoundingBox.msg
when i use from darknet_ros.msgs.msg import BoundingBoxes. and i don't know the means in BoundingBox.msg:
  

> float64 probability
> int64 xmin
> int64 ymin
> int64 xmax
> int64 ymax
> int16 id
> string Class

![2020-06-28 17-05-25屏幕截图](https://user-images.githubusercontent.com/23580110/85943270-9fab6e80-b961-11ea-8c19-61567d336835.png)

for example: the darknet_ros reconginze the car's probability is 87.6%
My question is : ` the int64 xmin, int64 ymin, int64 xmax, int64 ymax means?`
I think the Coordinates are three-dimensional  。but there is two-dimensional.
if this , the exactly define xmin, ymin, xmax, ymax, id  is ? how to define this  coordinate in the window?

**Comment by tomlankhorst** [comment]
These values are the locations of the borders of the bounding box that you see in the image. 
So `xmax-xmin` is the width and `ymax-ymin` is the height of the box. 
Darknet recognizes objects in a two dimensional image and to allow for drawing a nice box around the recognized object, the BoundingBox message contains the corresponding bounds-of-the-box.
