### ISSUE TITLE
test image display predictions.jpg is wrong

### ISSUE THREAD

**Issue by liangpu597** [leggedrobotics/darknet_ros#259]
I train use my own data. and when I finish train, I use: 
`./darknet detector test **/obj.data cfg/***.cfg backup/***tiny.weights`
I input an image path, and in darknet root I get the predictions.jpg this:
![predictions](https://user-images.githubusercontent.com/23580110/91790726-0e4bc780-ec44-11ea-8278-2b3183cf2edf.jpg)

I think the true is like this:
![](https://gitee.com/robin_shaun/XTDrone/raw/master/sensing/object_detection_and_tracking/YOLO/darknet_ros/darknet_ros/doc/test_detection.png)

please tell me how to do?  I would really appreciate it ！

**Comment by tomlankhorst** [comment]
Can you retry with latest release?
