### ISSUE TITLE
How can i get distance and x,y coordinates from object?

### ISSUE THREAD

**Issue by godyun7** [leggedrobotics/darknet_ros#262]
Hi I'm new in ROS for project. I use darknet_ros yolo. I want to get distance and x,y coordinates. but if i launch yolo_v3.launch file 
![Screenshot from 2020-09-24 09-44-53](https://user-images.githubusercontent.com/67062827/94129597-1534b700-fe4b-11ea-8724-c540b0e6f7b1.png). I can't get any coordinate information from object and bounding boxes. how can i get coordinates information. please teach me detail! please please

**Comment by fgonzalezr1998** [comment]
Hi @godyun7 I recommend you to use [this package](https://github.com/IntelligentRoboticsLabs/gb_visual_detection_3d)

**Comment by tomlankhorst** [comment]
Subscribe to the bounding box publisher and determine the values there.
