### ISSUE TITLE
Which CUDA version is compatible along with OpenCV 4.2

### ISSUE THREAD

**Issue by MattJWhyte** [leggedrobotics/darknet_ros#263]
Hi

I’ve made use of the recent pull request enabling OpenCV 4.2 support for the foxy branch of darknet_ros.

However, I am still getting an error related to OpenCV 4.2 requiring C++11 support. Could it potentially be related to the version of CUDA installed?

Which version of CUDA is known to work for the current darknet_ros?

Thanks for the help!

**Comment by sunt40** [comment]
mine is 9.0

**Comment by tomlankhorst** [comment]
Assuming this is resolved, otherwise try with the latest (Noetic) release.
