### ISSUE TITLE
darknet_ros catkin_make issue

### ISSUE THREAD

**Issue by mpheng666** [leggedrobotics/darknet_ros#265]
Hi I have problem with caktin_make the darknet_ros pkg, any idea how to solve it?

lycoris@lycoris-work-station:~/catkin_ws$ catkin_make -DCMAKE_BUILD_TYPE=Release
Base path: /home/lycoris/catkin_ws
Source space: /home/lycoris/catkin_ws/src
Build space: /home/lycoris/catkin_ws/build
Devel space: /home/lycoris/catkin_ws/devel
Install space: /home/lycoris/catkin_ws/install
####
####
####
####
[  0%] Built target std_msgs_generate_messages_nodejs
[  0%] Built target geometry_msgs_generate_messages_nodejs
[  0%] Built target std_msgs_generate_messages_eus
[  0%] Built target geometry_msgs_generate_messages_eus
[  0%] Built target std_msgs_generate_messages_lisp
[  0%] Built target geometry_msgs_generate_messages_lisp
[  0%] Built target geometry_msgs_generate_messages_cpp
[  0%] Built target std_msgs_generate_messages_cpp
[  0%] Built target _subt_msgs_generate_messages_check_deps_PoseFromArtifact
[  0%] Built target _subt_msgs_generate_messages_check_deps_SetPose
[  0%] Built target _subt_msgs_generate_messages_check_deps_Bind
[  0%] Built target _subt_msgs_generate_messages_check_deps_Unregister
[  0%] Built target _subt_msgs_generate_messages_check_deps_Register
[  0%] Built target _subt_msgs_generate_messages_check_deps_DatagramRos
[  0%] Built target geometry_msgs_generate_messages_py
[  0%] Built target flipper_control_plugin
[  0%] Built target std_msgs_generate_messages_py
[  0%] Built target laser_rotate_plugin
[  1%] Built target subt_rf_range_model
[  1%] Built target rosgraph_msgs_generate_messages_py
[  1%] Built target roscpp_generate_messages_py
[  1%] Built target roscpp_generate_messages_nodejs
[  1%] Built target subt_communication_broker_protobuf_compilation
[  1%] Built target roscpp_generate_messages_eus
[  1%] Built target _x2_msgs_generate_messages_check_deps_Drive
[  1%] Built target roscpp_generate_messages_lisp
[  1%] Built target rosgraph_msgs_generate_messages_cpp
[  1%] Built target roscpp_generate_messages_cpp
[  1%] Built target rosgraph_msgs_generate_messages_nodejs
[  1%] Built target _x2_msgs_generate_messages_check_deps_Feedback
[  1%] Built target rosgraph_msgs_generate_messages_eus
[  1%] Built target _x2_msgs_generate_messages_check_deps_Status
[  1%] Built target _x2_msgs_generate_messages_check_deps_DriveFeedback
[  1%] Built target rosgraph_msgs_generate_messages_lisp
[  2%] Built target protobuf_compilation
[  4%] Built target level_generator
Unpacking cave_circuit_practice_02.dat.zip
[  4%] Built target log_checker
[  6%] Built target dot_generator
x cave_circuit_practice_02.dat
[  6%] Built target _darknet_ros_msgs_generate_messages_check_deps_CheckForObjectsActionGoal
[  6%] Built target _darknet_ros_msgs_generate_messages_check_deps_CheckForObjectsAction
[  7%] Built target world_generator_cave
[  7%] Built target _darknet_ros_msgs_generate_messages_check_deps_ObjectCount
[  7%] Built target sensor_msgs_generate_messages_py
[  7%] Built target actionlib_msgs_generate_messages_py
[  7%] Built target _darknet_ros_msgs_generate_messages_check_deps_CheckForObjectsActionFeedback
[  7%] Built target _darknet_ros_msgs_generate_messages_check_deps_CheckForObjectsResult
[  7%] Built target _darknet_ros_msgs_generate_messages_check_deps_BoundingBoxes
[  7%] Built target _darknet_ros_msgs_generate_messages_check_deps_CheckForObjectsActionResult
[  7%] Built target sensor_msgs_generate_messages_cpp
[  7%] Built target actionlib_msgs_generate_messages_cpp
[  7%] Built target actionlib_msgs_generate_messages_nodejs
[  7%] Built target sensor_msgs_generate_messages_nodejs
[  7%] Built target sensor_msgs_generate_messages_lisp
[  7%] Built target actionlib_msgs_generate_messages_eus
[  7%] Built target sensor_msgs_generate_messages_eus
[  7%] Built target _darknet_ros_msgs_generate_messages_check_deps_CheckForObjectsGoal
[  7%] Built target actionlib_msgs_generate_messages_lisp
[  7%] Built target nav_msgs_generate_messages_py
[  7%] Built target _darknet_ros_msgs_generate_messages_check_deps_CheckForObjectsFeedback
[  7%] Built target trajectory_msgs_generate_messages_cpp
[  7%] Built target _catkin_empty_exported_target
[  7%] Built target mav_msgs_generate_messages_nodejs
[  7%] Built target _darknet_ros_msgs_generate_messages_check_deps_BoundingBox
[  7%] Built target trajectory_msgs_generate_messages_eus
[  7%] Built target nav_msgs_generate_messages_cpp
[  7%] Built target trajectory_msgs_generate_messages_nodejs
[  7%] Built target mav_msgs_generate_messages_cpp
[  7%] Built target mav_msgs_generate_messages_py
[  7%] Built target mav_msgs_generate_messages_eus
[  7%] Built target mav_msgs_generate_messages_lisp
[  7%] Built target trajectory_msgs_generate_messages_lisp
[  7%] Built target trajectory_msgs_generate_messages_py
[  7%] Built target nav_msgs_generate_messages_eus
[  7%] Built target nav_msgs_generate_messages_lisp
[  7%] Built target nav_msgs_generate_messages_nodejs
[  7%] Built target actionlib_generate_messages_py
[  7%] Built target topic_tools_generate_messages_py
[  7%] Built target actionlib_generate_messages_nodejs
[  7%] Built target actionlib_generate_messages_cpp
[  7%] Built target actionlib_generate_messages_eus
[  7%] Built target actionlib_generate_messages_lisp
[  7%] Built target tf2_msgs_generate_messages_py
[  7%] Built target tf2_msgs_generate_messages_eus
[  7%] Built target tf2_msgs_generate_messages_nodejs
[  7%] Built target tf2_msgs_generate_messages_lisp
[  7%] Built target tf2_msgs_generate_messages_cpp
[  7%] Built target topic_tools_generate_messages_cpp
[  7%] Built target topic_tools_generate_messages_lisp
[  7%] Built target topic_tools_generate_messages_nodejs
[  7%] Built target topic_tools_generate_messages_eus
[  9%] Built target subt_msgs_generate_messages_lisp
[ 12%] Built target subt_msgs_generate_messages_eus
[ 16%] Built target subt_msgs_generate_messages_nodejs
[ 16%] Built target subt_msgs_generate_messages_cpp
[ 17%] Built target x2_msgs_generate_messages_nodejs
[ 19%] Built target x2_msgs_generate_messages_cpp
[ 23%] Built target subt_msgs_generate_messages_py
[ 25%] Built target x2_msgs_generate_messages_lisp
[ 25%] Built target subt_communication_model
[ 25%] Built target _subt_ros_generate_messages_check_deps_CompetitionClock
[ 25%] Built target _subt_example_generate_messages_check_deps_CreatePeer
[ 27%] Built target x2_msgs_generate_messages_py
[ 28%] Built target x2_msgs_generate_messages_eus
[ 31%] Built target darknet_ros_msgs_generate_messages_py
[ 32%] Built target SubtCommsProtobuf
[ 36%] Built target darknet_ros_msgs_generate_messages_cpp
[ 37%] Built target SubtProtobuf
[ 43%] Built target darknet_ros_msgs_generate_messages_lisp
[ 45%] Built target darknet_ros_msgs_generate_messages_nodejs
[ 49%] Built target darknet_ros_msgs_generate_messages_eus
[ 49%] Built target subt_ros_generate_messages_py
[ 50%] Built target subt_ros_generate_messages_nodejs
[ 50%] Built target subt_ros_generate_messages_cpp
[ 50%] Built target subt_ros_generate_messages_lisp
[ 51%] Built target subt_ros_generate_messages_eus
[ 51%] Built target subt_example_generate_messages_lisp
[ 51%] Built target subt_example_generate_messages_py
[ 52%] Built target subt_example_generate_messages_eus
[ 52%] Built target subt_example_generate_messages_cpp
[ 52%] Built target subt_msgs_generate_messages
[ 53%] Built target subt_example_generate_messages_nodejs
[ 53%] Built target x2_msgs_generate_messages
[ 54%] Building NVCC (Device) object darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/__/darknet/src/darknet_ros_lib_generated_activation_kernels.cu.o
[ 56%] Building NVCC (Device) object darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/__/darknet/src/darknet_ros_lib_generated_avgpool_layer_kernels.cu.o
[ 56%] Building NVCC (Device) object darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/__/darknet/src/darknet_ros_lib_generated_maxpool_layer_kernels.cu.o
[ 57%] Building NVCC (Device) object darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/__/darknet/src/darknet_ros_lib_generated_deconvolutional_kernels.cu.o
[ 57%] Building NVCC (Device) object darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/__/darknet/src/darknet_ros_lib_generated_crop_layer_kernels.cu.o
[ 57%] Built target darknet_ros_msgs_generate_messages
[ 57%] Built target subt_ros_generate_messages
[ 57%] Built target roll_pitch_yawrate_thrust_controller_node
[ 57%] Building NVCC (Device) object darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/__/darknet/src/darknet_ros_lib_generated_blas_kernels.cu.o
[ 58%] Built target subt_communication_client
[ 59%] Built target subt_communication_broker
[ 59%] Built target subt_example_generate_messages
[ 59%] Building NVCC (Device) object darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/__/darknet/src/darknet_ros_lib_generated_dropout_layer_kernels.cu.o
[ 60%] Building NVCC (Device) object darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/__/darknet/src/darknet_ros_lib_generated_col2im_kernels.cu.o
[ 60%] Building NVCC (Device) object darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/__/darknet/src/darknet_ros_lib_generated_im2col_kernels.cu.o
[ 60%] Built target ArtifactValidator
[ 61%] Built target CommsBrokerPlugin
[ 61%] Building NVCC (Device) object darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/__/darknet/src/darknet_ros_lib_generated_convolutional_kernels.cu.o
[ 62%] Built target GasEmitterDetectorPlugin
[ 64%] Built target validate_connections
[ 64%] Built target unzip_dat
[ 67%] Built target ConnectionValidator
[ 68%] Built target VisibilityPlugin
[ 68%] Built target GameLogicPlugin
Scanning dependencies of target ControllerPlugin
Scanning dependencies of target BaseStationPlugin
/home/lycoris/catkin_ws/src/darknet_ros/darknet/src/crop_layer_kernels.cu:3:10: fatal error: cublas_v2.h: No such file or directory
 #include "cublas_v2.h"
          ^~~~~~~~~~~~~
compilation terminated.
/home/lycoris/catkin_ws/src/darknet_ros/darknet/src/maxpool_layer_kernels.cu:3:10: fatal error: cublas_v2.h: No such file or directory
 #include "cublas_v2.h"
          ^~~~~~~~~~~~~
/home/lycoris/catkin_ws/src/darknet_ros/darknet/src/dropout_layer_kernels.cu:3:10: fatal error: cublas_v2.h: No such file or directory
 #include "cublas_v2.h"
          ^~~~~~~~~~~~~
/home/lycoris/catkin_ws/src/darknet_ros/darknet/src/avgpool_layer_kernels.cu:3:10: fatal error: cublas_v2.h: No such file or directory
 #include "cublas_v2.h"
          ^~~~~~~~~~~~~
/home/lycoris/catkin_ws/src/darknet_ros/darknet/src/col2im_kernels.cu:3:10: fatal error: cublas_v2.h: No such file or directory
 #include "cublas_v2.h"
          ^~~~~~~~~~~~~
compilation terminated.
compilation terminated.
/home/lycoris/catkin_ws/src/darknet_ros/darknet/src/im2col_kernels.cu:3:10: fatal error: cublas_v2.h: No such file or directory
 #include "cublas_v2.h"
          ^~~~~~~~~~~~~
compilation terminated.
/home/lycoris/catkin_ws/src/darknet_ros/darknet/src/blas_kernels.cu:3:10: fatal error: cublas_v2.h: No such file or directory
 #include "cublas_v2.h"
          ^~~~~~~~~~~~~
/home/lycoris/catkin_ws/src/darknet_ros/darknet/src/convolutional_kernels.cu:3:10: fatal error: cublas_v2.h: No such file or directory
 #include "cublas_v2.h"
          ^~~~~~~~~~~~~
compilation terminated.
/home/lycoris/catkin_ws/src/darknet_ros/darknet/src/deconvolutional_kernels.cu:3:10: fatal error: cublas_v2.h: No such file or directory
 #include "cublas_v2.h"
          ^~~~~~~~~~~~~
compilation terminated.
/home/lycoris/catkin_ws/src/darknet_ros/darknet/src/activation_kernels.cu:3:10: fatal error: cublas_v2.h: No such file or directory
 #include "cublas_v2.h"
          ^~~~~~~~~~~~~
compilation terminated.
compilation terminated.
compilation terminated.
compilation terminated.
CMake Error at darknet_ros_lib_generated_im2col_kernels.cu.o.Release.cmake:219 (message):
  Error generating
  /home/lycoris/catkin_ws/build/darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/__/darknet/src/./darknet_ros_lib_generated_im2col_kernels.cu.o

CMake Error at darknet_ros_lib_generated_deconvolutional_kernels.cu.o.Release.cmake:219 (message):
  Error generating
  /home/lycoris/catkin_ws/build/darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/__/darknet/src/./darknet_ros_lib_generated_deconvolutional_kernels.cu.o

CMake Error at darknet_ros_lib_generated_blas_kernels.cu.o.Release.cmake:219 (message):
  Error generating
  /home/lycoris/catkin_ws/build/darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/__/darknet/src/./darknet_ros_lib_generated_blas_kernels.cu.o

CMake Error at darknet_ros_lib_generated_convolutional_kernels.cu.o.Release.cmake:219 (message):
  Error generating
  /home/lycoris/catkin_ws/build/darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/__/darknet/src/./darknet_ros_lib_generated_convolutional_kernels.cu.o

CMake Error at darknet_ros_lib_generated_avgpool_layer_kernels.cu.o.Release.cmake:219 (message):
  Error generating
  /home/lycoris/catkin_ws/build/darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/__/darknet/src/./darknet_ros_lib_generated_avgpool_layer_kernels.cu.o

CMake Error at darknet_ros_lib_generated_crop_layer_kernels.cu.o.Release.cmake:219 (message):
  Error generating
  /home/lycoris/catkin_ws/build/darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/__/darknet/src/./darknet_ros_lib_generated_crop_layer_kernels.cu.o

CMake Error at darknet_ros_lib_generated_col2im_kernels.cu.o.Release.cmake:219 (message):
  Error generating
  /home/lycoris/catkin_ws/build/darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/__/darknet/src/./darknet_ros_lib_generated_col2im_kernels.cu.o

CMake Error at darknet_ros_lib_generated_dropout_layer_kernels.cu.o.Release.cmake:219 (message):
  Error generating
  /home/lycoris/catkin_ws/build/darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/__/darknet/src/./darknet_ros_lib_generated_dropout_layer_kernels.cu.o

CMake Error at darknet_ros_lib_generated_activation_kernels.cu.o.Release.cmake:219 (message):
  Error generating
  /home/lycoris/catkin_ws/build/darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/__/darknet/src/./darknet_ros_lib_generated_activation_kernels.cu.o

darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/build.make:119: recipe for target 'darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/__/darknet/src/darknet_ros_lib_generated_convolutional_kernels.cu.o' failed
make[2]: *** [darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/__/darknet/src/darknet_ros_lib_generated_convolutional_kernels.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/build.make:77: recipe for target 'darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/__/darknet/src/darknet_ros_lib_generated_avgpool_layer_kernels.cu.o' failed
make[2]: *** [darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/__/darknet/src/darknet_ros_lib_generated_avgpool_layer_kernels.cu.o] Error 1
darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/build.make:84: recipe for target 'darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/__/darknet/src/darknet_ros_lib_generated_deconvolutional_kernels.cu.o' failed
make[2]: *** [darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/__/darknet/src/darknet_ros_lib_generated_deconvolutional_kernels.cu.o] Error 1
darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/build.make:91: recipe for target 'darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/__/darknet/src/darknet_ros_lib_generated_blas_kernels.cu.o' failed
make[2]: *** [darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/__/darknet/src/darknet_ros_lib_generated_blas_kernels.cu.o] Error 1
darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/build.make:98: recipe for target 'darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/__/darknet/src/darknet_ros_lib_generated_dropout_layer_kernels.cu.o' failed
make[2]: *** [darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/__/darknet/src/darknet_ros_lib_generated_dropout_layer_kernels.cu.o] Error 1
CMake Error at darknet_ros_lib_generated_maxpool_layer_kernels.cu.o.Release.cmake:219 (message):
  Error generating
  /home/lycoris/catkin_ws/build/darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/__/darknet/src/./darknet_ros_lib_generated_maxpool_layer_kernels.cu.o

darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/build.make:112: recipe for target 'darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/__/darknet/src/darknet_ros_lib_generated_im2col_kernels.cu.o' failed

make[2]: *** [darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/__/darknet/src/darknet_ros_lib_generated_im2col_kernels.cu.o] Error 1
darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/build.make:63: recipe for target 'darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/__/darknet/src/darknet_ros_lib_generated_activation_kernels.cu.o' failed
make[2]: *** [darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/__/darknet/src/darknet_ros_lib_generated_activation_kernels.cu.o] Error 1
darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/build.make:70: recipe for target 'darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/__/darknet/src/darknet_ros_lib_generated_crop_layer_kernels.cu.o' failed
make[2]: *** [darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/__/darknet/src/darknet_ros_lib_generated_crop_layer_kernels.cu.o] Error 1
darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/build.make:105: recipe for target 'darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/__/darknet/src/darknet_ros_lib_generated_col2im_kernels.cu.o' failed
make[2]: *** [darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/__/darknet/src/darknet_ros_lib_generated_col2im_kernels.cu.o] Error 1
darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/build.make:126: recipe for target 'darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/__/darknet/src/darknet_ros_lib_generated_maxpool_layer_kernels.cu.o' failed
make[2]: *** [darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/__/darknet/src/darknet_ros_lib_generated_maxpool_layer_kernels.cu.o] Error 1
CMakeFiles/Makefile2:6155: recipe for target 'darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/all' failed
make[1]: *** [darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Scanning dependencies of target pose_tf_broadcaster
Scanning dependencies of target optical_frame_publisher
Scanning dependencies of target subt_ros_relay
Scanning dependencies of target bridge_logger
Scanning dependencies of target set_pose_relay
[ 68%] Building CXX object subt/subt_ros/CMakeFiles/optical_frame_publisher.dir/src/OpticalFramePublisher.cc.o
[ 68%] Building CXX object subt/subt_ros/CMakeFiles/pose_tf_broadcaster.dir/src/pose_tf_broadcaster.cpp.o
[ 68%] Building CXX object subt/subt_ros/CMakeFiles/bridge_logger.dir/src/BridgeLogger.cc.o
[ 69%] Building CXX object subt/subt_ros/CMakeFiles/set_pose_relay.dir/src/SetPoseRelay.cc.o
[ 70%] Building CXX object subt/subt_ros/CMakeFiles/subt_ros_relay.dir/src/SubtRosRelay.cc.o
[ 70%] Building CXX object subt/subt_ign/CMakeFiles/ControllerPlugin.dir/src/ControllerPlugin.cc.o
[ 70%] Building CXX object subt/subt_ign/CMakeFiles/BaseStationPlugin.dir/src/BaseStationPlugin.cc.o
[ 70%] Linking CXX executable /home/lycoris/catkin_ws/devel/lib/subt_ros/pose_tf_broadcaster
[ 70%] Built target pose_tf_broadcaster
[ 71%] Linking CXX executable /home/lycoris/catkin_ws/devel/lib/subt_ros/optical_frame_publisher
[ 71%] Built target optical_frame_publisher
[ 72%] Linking CXX executable /home/lycoris/catkin_ws/devel/lib/subt_ros/bridge_logger
[ 72%] Built target bridge_logger
[ 72%] Linking CXX executable /home/lycoris/catkin_ws/devel/lib/subt_ros/set_pose_relay
[ 73%] Linking CXX shared library /home/lycoris/catkin_ws/devel/lib/libControllerPlugin.so
[ 73%] Built target ControllerPlugin
[ 73%] Built target set_pose_relay
[ 74%] Linking CXX shared library /home/lycoris/catkin_ws/devel/lib/libBaseStationPlugin.so
[ 74%] Built target BaseStationPlugin
[ 74%] Linking CXX executable /home/lycoris/catkin_ws/devel/lib/subt_ros/subt_ros_relay
[ 74%] Built target subt_ros_relay
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j12 -l12" failed

![Screenshot from 2020-10-01 23-43-11](https://user-images.githubusercontent.com/45779508/94832295-4e1eee00-0440-11eb-863c-657cf2eba16a.png)

**Comment by dharanish-nh** [comment]
https://github.com/leggedrobotics/darknet_ros/issues/12#issuecomment-310914566

**Comment by tomlankhorst** [comment]
Please reopen if the suggested fix did not work.
