### ISSUE TITLE
libdarknet_ros_lib.so：undefined reference to‘cvIplImage(cv::Mat const&)’

### ISSUE THREAD

**Issue by Guozhengxiang** [leggedrobotics/darknet_ros#269]
Linking CXX executable /home/froven/catkin_ws/devel/lib/darknet_ros/darknet_ros/home/froven/catkin_ws/devel/lib/libdarknet_ros_lib.so：undefined reference to‘cvIplImage(cv::Mat const&)’

**Comment by tomlankhorst** [comment]
Which OpenCV version are you using? Please provide more info about your operating system etc.
