### ISSUE TITLE
 #  error "OpenCV 4.x+ requires enabled C++11 support"

### ISSUE THREAD

**Issue by z760** [leggedrobotics/darknet_ros#276]
/usr/include/opencv4/opencv2/core/cvdef.h:690:4: error: #error "OpenCV 4.x+ requires enabled C++11 support"
 #  error "OpenCV 4.x+ requires enabled C++11 support"
thannk you !!

**Comment by tomlankhorst** [comment]
Enable C++11 support. Please provide more background info if that does not solve your issue.
