### ISSUE TITLE
Software versions compatibility 

### ISSUE THREAD

**Issue by reem90** [leggedrobotics/darknet_ros#280]
What are the exact versions for the following software that are used to build this package without any errors? What are the versions that are compatible with each other? 

ROS
Python 
Cuda
OpenCV 

Also, should we consider versions of other packages when installing this package ??

**Comment by tomlankhorst** [comment]
1. ROS Noetic = Ubuntu Focal + system-default Python and OpenCV. 
2. ROS Melodic = Ubuntu Bionic + system-default Python and OpenCV.

See the CI pipeline for a working config: https://github.com/leggedrobotics/darknet_ros/blob/master/.github/workflows/catkin-build.yml. 

Corresponding CUDA Toolkit for the OS: [developer.nvidia.com](https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu)
