### ISSUE TITLE
Ubuntu 20 and YOLO on ROS Noetic possible?

### ISSUE THREAD

**Issue by RobbieTheK** [leggedrobotics/darknet_ros#291]
Is there a way to get darknet_ros working in Ubuntu 20? So far I see it's only tested for  [Ubuntu 18](https://github.com/leggedrobotics/darknet_ros "Ubuntu 18")

Many errors when trying to compile. Any tutorial or tips to work around the errors?

**Comment by elpidiovaldez** [comment]
I followed the procedure given by bigrobinson [here](https://github.com/leggedrobotics/darknet_ros/issues/290).  It worked !
