### ISSUE TITLE
no object detected

### ISSUE THREAD

**Issue by 3bobo** [leggedrobotics/darknet_ros#297]
Hi, I met some error when I `roslaunch darknet_ros darknet_ros.launch `, I used `usb_cam` to get the camera image, the topic is `/usb_cam/image_raw`, and I also changed the corresponding topic in `ros.yaml`. The error is, the launch could successfully run, but no object detected, whatever I tried, it only outputs

> FPS:24.5
> Objects:
> 
> 
> 
> 
> FPS:22.9
> Objects:

I check the topic `/usb_cam/image_raw` that it has been corrected sent to `darknet_ros` node, and in rviz it shows the image successfully, therefore I don't know where is the problem.

**Comment by wildpig888** [comment]
I met the same problems. Can anyone help?

**Comment by wildpig888** [comment]
> Hi, I met some error when I `roslaunch darknet_ros darknet_ros.launch `, I used `usb_cam` to get the camera image, the topic is `/usb_cam/image_raw`, and I also changed the corresponding topic in `ros.yaml`. The error is, the launch could successfully run, but no object detected, whatever I tried, it only outputs
> 
> > FPS:24.5
> > Objects:
> > FPS:22.9
> > Objects:
> 
> I check the topic `/usb_cam/image_raw` that it has been corrected sent to `darknet_ros` node, and in rviz it shows the image successfully, therefore I don't know where is the problem.

Which version did you use, yolov3 or AB?

**Comment by 3bobo** [comment]
@wildpig888 sorry for reply late, I use yolov3 and it doesn't work. Finally I copy a new version from my friend and it works, thus I still do not know why it does not work at first.

**Comment by tomlankhorst** [comment]
You copied what, exactly?

**Comment by wildpig888** [comment]
> @wildpig888 sorry for reply late, I use yolov3 and it doesn't work. Finally I copy a new version from my friend and it works, thus I still do not know why it does not work at first.
No detection in darknet_ros, while darknet is detecting with the same .weights #307
You can see if it will work.

**Comment by wildpig888** [comment]
> @wildpig888 sorry for reply late, I use yolov3 and it doesn't work. Finally I copy a new version from my friend and it works, thus I still do not know why it does not work at first.

No detection in darknet_ros, while darknet is detecting with the same .weights #307
You can see if it will work.

**Comment by 3bobo** [comment]
> You copied what, exactly?

The whole project he downloaded before.

**Comment by tomlankhorst** [comment]
Hope your issues are resolved. If you want to know more, please provide detailed info.
