### ISSUE TITLE
Don't want the image window to display 

### ISSUE THREAD

**Issue by Tanguyvans** [leggedrobotics/darknet_ros#306]
Hi, 
I am trying to edit the so that I don't have the output image with the bounding boxes. But the rest should work as usual.
How can I do that?

I am using : roslaunch darknet_ros darknet_ros.launch

**Comment by tomlankhorst** [comment]
Set the parameter `image_view/enable_opencv` to false.

**Comment by zerosnsa** [comment]
Set the parameter to false.image_view/enable_opencv，What happens when I use the rqt node to view the screen
![Uploading 1714377573439.png…]()

**Comment by zerosnsa** [comment]
Set this parameter to false. When I use the rqt node to view the screen, the screen display is Mosaic
![1714377683764](https://github.com/leggedrobotics/darknet_ros/assets/152005489/8bc9848d-086e-4e81-a698-668afc3a72ef)
