### ISSUE TITLE
Memory Leak 

### ISSUE THREAD

**Issue by rptamin** [leggedrobotics/darknet_ros#311]
I am using darknet_ros on the Nvidia NX. I am running into a memory leak error. 8gb of ram is used up in 30 seconds and then the node crashed. I have CUDA and GPU enabled but not opencv as I am using a gscam pipeline.

**Comment by mbjelonic** [comment]
In my case, the memory is not leaking. Here you can see my output of nvidia-smi:
![image](https://user-images.githubusercontent.com/22881556/115364504-bdcdae00-a1c3-11eb-8257-d25a533661af.png)
Are you up-to-date with master?

**Comment by rptamin** [comment]
Yes, I am up to date with Master. Last commit was 11 days ago, and I pulled after that date. It may have to do with my camera gstreamer pipeline. Thanks for checking!

**Comment by rptamin** [comment]
After further inspection, I have a few questions:
1. Does darknet use OpenCV for the output of the real-time video?
2. I have OpenCV not enabled, but I do get a window with yolo working. What is in charge of this?

**Comment by xunil17** [comment]
Hello, I'm running into the same issues using Ubuntu 20.04 and the node uses up almost half of my system memory within 10-15 seconds. 
![Screenshot from 2021-04-26 21-48-04](https://user-images.githubusercontent.com/12092234/116177267-21327100-a6d9-11eb-93e6-7f7317d88092.png)

**Comment by rptamin** [comment]
I believe it is indeed an issue with darknet_ros. My team and I tested other components using valgrind, and it points to a issue with darknet_ros.

**Comment by girlrush** [comment]
HI, I use ubuntu 16.04, GTX950M. I have same error too. While running darknet ros, My memory usage continues to grow.
here is my CMakeLists. Is this problem?
![CMakeLists](https://user-images.githubusercontent.com/70830088/116766856-a9ad6a80-aa67-11eb-9a56-5b1caac48eab.png)

**Comment by FPSychotic** [comment]
Same problem here, Jetson Xavier NX, opencv 4.1.1  compiled with cuda and cudnn, it eats 8gb of ram of and 16GB of swap in 3 minutes.
Download with SSH and Melodic branch.
The master branch without SSH download didn't  compile.

**Comment by joydeep-b** [comment]
Confirmed there is a memory leak on master and release branches, tested on 20.04 + Noetic on x86_64 with an RTX2080, and also on 18.04+Melodic on Jetson TX2.

**Comment by anshulsood-02** [comment]
Same here. Tested on 20.04 + noetic on x86_64 with RTX 2060ti

**Comment by darkhan-s** [comment]
@mbjelonic Also confirmed on 20.04, core i7, 32gb ram and nvidia P3200, freezes completely in a minute or so.

**Comment by mbjelonic** [comment]
I looked into this issue again and last time I only checked the GPU usage but as correctly noted here, it is a memory leak in RAM. Thanks to everyone for pointing this out!

It took me 2 hours of debugging and only one line of code to fix this. Sometimes it is clearly not about the amount of code. :)

For future tests, I added a Valgrind launch file for faster debugging.

Can you please check out the next commit and see if this fixes the issue?

**Comment by anshulsood-02** [comment]
Thank you, it is working now!

**Comment by mbjelonic** [comment]
@anshulsood-02 great, thanks for letting me know.

**Comment by joydeep-b** [comment]
Confirmed that the fix is good, thanks for looking into it!

**Comment by ddhxm** [comment]
Thank you so much!!!
