### ISSUE TITLE
the version of darknet_ros with tensorrt?  

### ISSUE THREAD

**Issue by xielock** [leggedrobotics/darknet_ros#312]
Could i find  the open source ?

**Comment by tomlankhorst** [comment]
You are looking for a version of darknet_ros with tensorrt, is that correct? 

For what purpose? Did you find what you were looking for in the meanwhile?

**Comment by xielock** [comment]
Yes！I have finished it. I want to accelerate the process of the inference.

**Comment by 001zwzwzw** [comment]
hello which method you finish it,i also want to use tensorrt tu accelerate darknet_ros on jeston nx @xielock

**Comment by zerosnsa** [comment]
> 是的！我已经完成了。我想加快推理过程。
How do you accelerate it? How many frames can you reach
