### ISSUE TITLE
YOLOros turns red staffs into blue staffs

### ISSUE THREAD

**Issue by SuperrHaze** [leggedrobotics/darknet_ros#331]
It seems that red exchanges with blue.
The left picture runs on yolo, the rights picture is the raw image which is in the correct color 
![20210618145203](https://user-images.githubusercontent.com/66858873/122519450-0e874900-d045-11eb-9323-003d78319de7.png)
i dont know how to solve it, so i decide to reinstall yoloros and i will comment if this problem is solved
probably the problem is input picture using opencv in yolo

**Comment by SuperrHaze** [comment]
I solve this problem。
AlexAB Daknet based on RGB and opencv read pictures on BGR
Alex has already converted BGR into RGB, so darknet works well.
But in YoloObjectDetector.cpp line:377 rgbgr_image(buff_[buffIndex_]);
RGB flips back to BGR,so just notes this sentence and the result turns great.

**Comment by johnny12150** [comment]
> I solve this problem。 AlexAB Daknet based on RGB and opencv read pictures on BGR Alex has already converted BGR into RGB, so darknet works well. But in YoloObjectDetector.cpp line:377 rgbgr_image(buff_[buffIndex_]); RGB flips back to BGR,so just notes this sentence and the result turns great.

I am facing this problem too. 
`rgbgr_image()` turns rgb into bgr and I try to use `cvtColor` with `cv::COLOR_BGR2RGB` to turn the color back in `publishInThread()`.
However, I still get the image of the wrong color that red exchanges into the blue.
