### ISSUE TITLE
catkin_make error (about opencv)

### ISSUE THREAD

**Issue by wang19950602** [leggedrobotics/darknet_ros#34]
Hello, I got a little problem with catkin_make.
I use ubuntu 14.04 , ROS:indigo , gcc version 4.8.4
When running 'catkin_make -DCMAKE_BUILD_TYPE=Release',I encounter a problem:
![catkin_make error](https://user-images.githubusercontent.com/32090473/30638267-6bd8099e-9e2d-11e7-8b9a-cc526a9bb60e.png)
The result shows that undefined reference to several opencv functions.
May I ask you how to fix this problem?
Thank you

**Comment by floft** [comment]
In *src/darknet_ros/darknet_ros/CMakeLists.txt*:
find the *target_link_libraries* and add ${OpenCV_LIBS} to the list ([src](https://answers.ros.org/question/57187/opencv-undefined-reference-problem/))

**Comment by floft** [comment]
Okay, so I'm on indigo and this appears to work:

    cd src/
    git clone https://github.com/superjax/cv3_bridge

In *src/darknet_ros/darknet_ros/CMakeLists.txt*:
* find the *cv_bridge* and replace with *cv3_bridge*
* find the *find_package(OpenCV REQUIRED)* and change to *find_package(OpenCV 3 REQUIRED)*
* find the *target_link_libraries(${PROJECT_NAME} ...* and add ${OpenCV_LIBRARIES} to the end of the list

**Comment by Achllle** [comment]
The fix by @floft worked on Kinetic, you have to additionally go into package.xml in darknet_ros and change `cv_bridge` to `cv3_bridge`.

**Comment by joyyang1215** [comment]
Add ${OpenCV_LIBS} and it works.
Thanks!

**Comment by araster1010** [comment]
I have same problem as you.
I tried cv3_bridge, but it doesn't work.

In the CMakelists.txt, there are 4 target_link_libraries.
Should I add ${OpenCV_LIBS} all of them?

Could you tell me more detail about this?

**Comment by mbjelonic** [comment]
You can have a look in the CMakeLists.txt of the branch devel/threads. I fixed it there. I will also merge this branch soon because the detection is much faster on this branch.

**Comment by mbjelonic** [comment]
Merged the branch devel/threads.
