### ISSUE TITLE
fatal error:darknet.h:No such file or directory 

### ISSUE THREAD

**Issue by lingogogo** [leggedrobotics/darknet_ros#351]
fatal error:darknet.h:No such file or directory 
#include "darknet.h"

However, i have the file in darknet/include/darknet.h
i have to write it on the file, so it can find the directory.
but i don't know how to do it

thank a lot in advance

**Comment by Ar-Ray-code** [comment]
There is too little information.
Please give me the directory information in `tree darknet_ros/`.

I think it is due to a failure to get the submodule.
Run 
```
$ cd <path-to-darknet_ros> 
$ git submodule update --init
```

**Comment by lingogogo** [comment]
thank for your answer 
i deal with the problem with correct path.
so it can take the darknet.h
