### ISSUE TITLE
Compilation error nvcc fatal

### ISSUE THREAD

**Issue by tiagojdias** [leggedrobotics/darknet_ros#39]
Can anyone help me with this compilation error?

nvcc fatal   : Stray '"' character
CMake Error at darknet_ros_lib_generated_deconvolutional_kernels.cu.o.Release.cmake:222 (message):
  Error generating

Thank you.

**Comment by astha736** [comment]
Hi, 

Maybe you can try removing "**set(CMAKE_CXX_FLAGS "-std=c++11 ${CMAKE_CXX_FLAGS}")**" from the darknet_ros_msgs/CMakeList.txt and add "**set( CUDA_PROPAGATE_HOST_FLAGS OFF )**" in darknet_ros_msgs/CMakeLists.txt and darknet_ros/CMakeLists.txt. 

I solved some of my issues with these modifications, including the errors for *cu.o files. I hope this helps.

**Comment by gangyahaidao** [comment]
it doesnot help to solve my problem

**Comment by zhanghming** [comment]
I have the same problem, and cannot solve it.
```
nvcc fatal   : Stray '"' character CMake Error at darknet_ros_lib_generated_maxpool_layer_kernels.cu.o.cmake:222 (message):
```
I don't know why

**Comment by Jichen66** [comment]
I also have the same problem and cannot solve it. Can anybody do me a favor?

**Comment by jianpursuit** [comment]
I also have the same problem and cannot solve it. Can anybody do me a favor?

**Comment by q8wwe** [comment]
i have same problem , How to solve?

**Comment by cmiller1990** [comment]
I think this is related to [this issue here](https://github.com/NVIDIA/gvdb-voxels/issues/2).

As suggested, upgrading cmake to 3.11.4 resolved the issue for me.

**Comment by tomlankhorst** [comment]
Should be resolved in recent versions.
