### ISSUE TITLE
Data format is being processed wrong (BGR instead of RGB)

### ISSUE THREAD

**Issue by dhiegomaga** [leggedrobotics/darknet_ros#43]
It took me _some hours_ to figure out why my trained network for custom object detection were not showing any bounding boxes when using in this particular implementation of darknet bridge... 

Well, it turns out that most neural networks are trained using the RGB color format (including mine), and in [this line](https://github.com/leggedrobotics/darknet_ros/blob/master/darknet_ros/src/YoloObjectDetector.cpp#L307) the image is being converted to BGR format. Changing it to: 

`cam_image = cv_bridge::toCvCopy(msg, sensor_msgs::image_encodings::RGB8);`

may give more accurate results - while making you look like an avatar if you're using OpenCV display, because opencv uses BGR formatting, because the alphabet..)

Most of this big networks out there are so well trained that they are robust to color channel swaps anyway, but if you're training against your own objects it might be an issue.

**Comment by mbjelonic** [comment]
Thank you for the help! I changed all the the BGR8 formatting into RGB8.

**Comment by Wuxinxiaoshifu** [comment]
> Most of this big networks out there are so well trained that they are robust to color channel swaps anyway, but if you're training against your own objects it might be an issue.

I also meet this problem!
when i training,the picture's format is rgb8. when i test the weights that i trained using bag,the colors of pictures in windows(yolo_v4) is different from  my training pictures.
i also changed BGR8 to RGB8 in YoloObjectDetector.CPP, but the colors in window(yolo_v4) didn't change!
how did you handled this problem?

**Comment by RuijieZhu94** [comment]
> st the weig

Perhaps you can directly change the format of msg encoding after cam_image was defined.
`cv_bridge::CvImagePtr cam_image;
try ..........`
cam_image = cv_bridge::toCvCopy(msg, "rgb8");
>
