### ISSUE TITLE
Undefined reference probelm

### ISSUE THREAD

**Issue by CCB307** [leggedrobotics/darknet_ros#53]
Hello, I got a little problem with catkin_make.
![image](https://user-images.githubusercontent.com/18183832/34905772-c5b71596-f89a-11e7-99c5-33ad4384cd65.png)
The result shows that undefined reference to YoloObjectDetector class constructor function.
May I ask you how to fix this problem?
Thank you
![image](https://user-images.githubusercontent.com/18183832/34905813-71570244-f89b-11e7-8d3c-6fc74f4d1496.png)

**Comment by tschmidt64** [comment]
Hard to debug without more info. Did you run `catkin clean` on it beforehand?

**Comment by ash22194** [comment]
I too had this problem. Cloning the repository with the recursive flag solved the problem. Check the readme.

**Comment by CCB307** [comment]
@tschmidt64 @ash22194 Thank you for your answer. I have resolved the issue. ^-^!!
