### ISSUE TITLE
Bounding box error

### ISSUE THREAD

**Issue by abeyang00** [leggedrobotics/darknet_ros#83]
@mbjelonic ,

Originally, when i use "demo" option with the original repository (pjreddie's), i get the result like

![39572955-33c0d7c6-4f0c-11e8-935a-7860cd90cd89](https://user-images.githubusercontent.com/36392866/39661200-cc64b538-5088-11e8-8995-bdee5d52d874.png)

but when i used this forked version, i get the result like
![39572967-3d92c048-4f0c-11e8-86da-a28156231773](https://user-images.githubusercontent.com/36392866/39661215-e6b05550-5088-11e8-98c3-a3d2e45673c1.png)

Do you have any idea what could be the issue? Will it have to do with nms? did you change something with the boudning boxes' (x,y, w,h) scale?

**Comment by mbjelonic** [comment]
Hi, what was the issue and how did you fix it?
Best,
Marko

**Comment by iamrajee** [comment]
@mbjelonic @abeyang00

How did you fixed it? I'm having the same issue. I tried increasing beta_nms and decreaseing iou_thresh to extreme in yolov4.cfg but no luck.
![Screenshot from 2021-10-18 19-06-54](https://user-images.githubusercontent.com/25712145/137742354-f08f5a4c-80f4-485b-b3dc-2a31bcfbc77a.png)
![Screenshot from 2021-10-18 19-11-08](https://user-images.githubusercontent.com/25712145/137743748-43baf04c-4a6c-4412-a717-cbec569b8a7d.png)
