### ISSUE TITLE
Couldn't open file: /default/yolov2-tiny.cfg

### ISSUE THREAD

**Issue by jsdd25** [leggedrobotics/darknet_ros#86]
I run the package by "rosrun darknet_ros darknet_ros"，and it say Couldn't open file: /default/yolov2-tiny.cfg.
Anybody have ideal?Thank you very much!

**Comment by mbjelonic** [comment]
The readme explains how to download the weights. Check out the readme and jump to the section ‘Download weights’.

**Comment by jsdd25** [comment]
Thank you very much! I have fixed this problem.

**Comment by QiuYilin** [comment]
so?
