### ISSUE TITLE
yolov3-voc.weights missing?

### ISSUE THREAD

**Issue by jokla** [leggedrobotics/darknet_ros#90]
Hi!

Where can I find the file yolov3-voc.weights?

I cannot download it from http://pjreddie.com/media/files/yolov3-voc.weights

Thanks!

**Comment by Chrislzy1993** [comment]
hi, @jokla , man, did u save it????

**Comment by marescpla** [comment]
Can someone help, please? I can't download the yolov3-voc.weights

**Comment by soulslicer** [comment]
how was this solved? is this package usable anymore?

**Comment by fwarmuth** [comment]
still missing, can someone upload it?

**Comment by altineller** [comment]
@fwarmuth I was looking for the same thing.

https://pjreddie.com/darknet/yolo/ site does not mention the yolov3-voc-weights

but github repository does. maybe it is obsoluted?

**Comment by mbjelonic** [comment]
Yes. The yolo-v3.weights is obsolete and therefore, I updated the readme. There is a http://pjreddie.com/media/files/yolov3-tiny.weights that can be used instead. There are more pre-trained weights from different data sets reported here: https://pjreddie.com/darknet/yolo/
