### ISSUE TITLE
Compilation error: c++: internal compiler error: Killed (program cc1plus)

### ISSUE THREAD

**Issue by lx704612715** [leggedrobotics/darknet_ros#92]
Hello, 

I use ROS Kinetic and Jetson Tx2. I met the following error by compilation. I have already changed my swap to solve it. But it doesn't work. Would you please give me some advice? Thank you in advanced.

![selection_004](https://user-images.githubusercontent.com/30981602/40621818-0cf6dc40-628e-11e8-8e68-d868f53dc747.png)

![image](https://user-images.githubusercontent.com/30981602/40621938-ace6fdf2-628e-11e8-8714-8c7d28013b83.png)

**Comment by ahmetsaglam** [comment]
Any help? I have the same issue for Jetson Nano when compiling ROS SLAM packages
